services:
  pgvectordb:
    build:
      context: .
      dockerfile: Dockerfile.pgvector-age
    image: perfmem-pgvector-age:latest
    container_name: perfmem-pgvector-age
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./data/pgvectordb:/var/lib/postgresql/18/docker
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
